Repository whitman-books-online/whitman-books-online, pull requests merged in 2018-04, with the labels that each got.

#44 create Page component and slight styling
  frontend/src/Exchange.js
  frontend/src/Page.js
  frontend/src/Sell.js
  frontend/src/index.css
Labels: frontend

#52 Add sphinx_js to Sphinx config
  docs/images/uml_use_case.png
  docs/source/conf.py
Labels: documentation

#47 Initial TOC and overall reorganization
  docs/images/Front-End-Design.png
  docs/source/dev-docs/sample.rst
  docs/source/index.rst
  docs/source/meeting/2018-01-23.rst
  docs/source/meeting/2018-01-24.rst
  docs/source/meeting/2018-01-30.rst
  docs/source/meeting/2018-01-31.rst
  docs/source/meeting/2018-02-05.rst
  docs/source/meeting/2018-02-06.rst
  docs/source/meeting/2018-02-20.rst
  docs/source/meeting/2018-02-27.rst
  docs/source/meeting/2018-02-28.rst
  docs/source/meeting/2018-03-27.rst
  docs/source/meeting/2018-04-03.rst
  docs/source/milestone/analysis-document.rst
  docs/source/milestone/ethical-concerns.rst
  docs/source/milestone/meeting-notes-workflow.rst
  docs/source/milestone/requirements-document.rst
  docs/source/usr-docs/sample.rst
Labels: documentation

#59 Fix typo in conf.py
  docs/source/conf.py
Labels: documentation

#71 Deploy frontend dev to an EC2 instance
  deploy/README.md
  deploy/frontend_dev.yml
  deploy/roles/frontend/defaults/main.yml
  deploy/roles/frontend/handlers/main.yml
  deploy/roles/frontend/tasks/main.yml
  deploy/roles/frontend/tasks/packages.yml
  deploy/roles/frontend/templates/frontend_service.j2
  deploy/staging
Labels: frontend, infrastructure

#77 Remove sphinx_js
  docs/source/conf.py
Labels: documentation

#108 The Grand Meeting Notes Reorganization
  README.md
  docs/source/index.rst
  docs/source/meeting/backend/2018-02-06.rst
  docs/source/meeting/backend/2018-02-28.rst
  docs/source/meeting/backend/2018-03-27.rst
  docs/source/meeting/backend/2018-04-03.rst
  docs/source/meeting/documentation/2018-01-30.rst
  docs/source/meeting/documentation/2018-02-05.rst
  docs/source/meeting/documentation/2018-02-06.rst
  docs/source/meeting/documentation/2018-02-27.rst
  docs/source/meeting/documentation/2018-04-11.rst
  docs/source/meeting/frontend/2018-01-26.rst
  docs/source/meeting/frontend/2018-01-30.rst
  docs/source/meeting/frontend/2018-02-02.rst
  docs/source/meeting/general/2018-01-23.rst
  docs/source/meeting/general/2018-01-24.rst
  docs/source/meeting/general/2018-01-30.rst
  docs/source/meeting/general/2018-01-31.rst
  docs/source/meeting/general/2018-02-06.rst
  docs/source/meeting/general/2018-02-20.rst
  docs/source/meeting/general/2018-02-27.rst
  docs/source/meeting/general/2018-04-03.rst
  docs/source/milestone/analysis-document.rst
  docs/source/milestone/design-document.rst
  docs/source/milestone/meeting-notes-workflow.rst
Labels: documentation

#114 Upload API guide
  docs/source/dev-docs/api_guide.rst
Labels: documentation

#129 Meeting notes index page + Adding rest of wiki to readthedocs
  docs/source/conf.py
  docs/source/dev-docs/lorem.rst
  docs/source/dev-docs/sample.rst
  docs/source/extra/analysis-document.rst
  docs/source/extra/design-document.rst
  docs/source/extra/ethical-concerns.rst
  docs/source/extra/helpful-links.rst
  docs/source/extra/meeting-notes-workflow.rst
  docs/source/extra/requirements-document.rst
  docs/source/index.rst
  docs/source/meeting/frontend/2018-02-05.rst
  docs/source/meeting/frontend/2018-02-06.rst
  docs/source/meeting/frontend/2018-02-09.rst
  docs/source/meeting/meeting-index.rst
  docs/source/usr-docs/lorem.rst
  docs/source/usr-docs/sample.rst
Labels: documentation

#131 Fixes to API guide
  docs/source/dev-docs/api_guide.rst
Labels: documentation

#140 Screengrabs for User Guide
  docs/images/Login Page.JPG
  docs/images/Market Page, Contacting Seller.JPG
  docs/images/Market Page.JPG
  docs/images/Profile Page, No Listings.JPG
  docs/images/Sell Page, ISBN Prompt.JPG
  docs/images/Sell Page, Inputting Condition.JPG
  docs/images/Sell Page, Inputting ISBN.JPG
  docs/images/Sell Page, Inputting Price.JPG
Labels: documentation

#147 Sphinx-autodoc setup
  backend/api/db.py
  docs/source/conf.py
  docs/source/dev-docs/app.rst
  docs/source/dev-docs/book.rst
  docs/source/dev-docs/db.rst
  docs/source/dev-docs/listing.rst
  docs/source/dev-docs/user.rst
Labels: documentation

#143 Adding user guide without images to documentation
  docs/source/usr-docs/userguide.rst
Labels: documentation

#151 Added table of contents for the autodocs
  docs/source/conf.py
  docs/source/dev-docs/api-guide.rst
  docs/source/dev-docs/app.rst
  docs/source/dev-docs/autodoc-index.rst
  docs/source/dev-docs/autodoc/app.rst
  docs/source/dev-docs/autodoc/book.rst
  docs/source/dev-docs/autodoc/db.rst
  docs/source/dev-docs/autodoc/listing.rst
  docs/source/dev-docs/autodoc/user.rst
  docs/source/dev-docs/book.rst
  docs/source/dev-docs/db.rst
  docs/source/dev-docs/listing.rst
  docs/source/dev-docs/lorem.rst
  docs/source/dev-docs/user.rst
  docs/source/index.rst
  docs/source/usr-docs/lorem.rst
Labels: documentation

#158 API authorization and tests for /user/<id> and /userlist/<ids>
  .gitignore
  backend/api/__init__.py
  backend/api/auth.py
  backend/api/book.py
  backend/api/user.py
  backend/requirements.txt
  backend/tests/__init__.py
  backend/tests/test_all.py
  backend/tests/test_api_base.py
  backend/tests/test_api_user.py
  backend/tests/test_auth.py
  scripts/get_jwt.py
  scripts/requirements.txt
Labels: api, backend
